### ISSUE TITLE
GeneratedBy error

### ISSUE THREAD

**Issue by wizofe** [PennLINC/xcp_d#308]
I am trying to use xcp_d via the singularity container with the following command:

```
singularity run --cleanenv xcp_d.simg /data/project/ABIDE/abide2/ /data/project/ABIDE/abide2/derivatives/ --participant-label 29666 --nthreads=26 --omp-nthreads 12 -p 36P -f 0.2
```

I am getting the following error:

```
    Running xcp_abcd version 0.0.9+0.g067fabf.dirty:
      * fMRI directory path: /data/project/ABIDE/abide2.
      * Participant list: ['29666'].
      * Run identifier: 20220407-140551_cd30d685-c663-447f-9399-4a486b740c16.


220407-14:08:33,360 nipype.utils WARNING:
	 A newer version (1.7.1) of nipy/nipype is available. You are using 1.7.0
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 486, in build_workflow
    retval['workflow'] = init_xcpd_wf (
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/base.py", line 145, in init_xcpd_wf
    single_subj_wf = init_subject_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/base.py", line 310, in init_subject_wf
    """.format(input_type=input_type,nipype_ver=nipype_ver,fvers=getfmriprepv(fmri_dir=fmri_dir))
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/base.py", line 475, in getfmriprepv
    fvers = datay['GeneratedBy'][0]['Version']
KeyError: 'GeneratedBy'
```
Any ideas? Thanks

**Comment by smeisler** [comment]
Hello,

You should point the `/data/project/ABIDE/abide2/derivatives/` argument to the **full path** to your preprocessed outputs, e.g. `/data/project/ABIDE/abide2/derivatives/fmriprep`

Best,
Steven

**Comment by wizofe** [comment]
Hi Steven, 

thank you for the pointer. I tried that but again I am getting the same error. The documentation isn't very clear about the paths, so could you help me further on this? 

The structure of my folder is like this: I have a folder `/data/project/ABIDE/abide2` which has the pre-processed fmriprep'ed files from the ABIDE consortium. Under this folder the subfolders have the subject numbers, i.e. 

```
sub-29022                 sub-29281.html  sub-29449       sub-29628.html  sub-51313.html
sub-29022.html            sub-29282       sub-29449.html  sub-29629       sub-51315
sub-29023                 sub-29282.html  sub-29450       sub-29629.html  sub-51315.html
sub-29023.html
```

Now if I enter one of those folders the structure looks like this:

```
(base) [k19012844@login2 sub-29666]0% tree
.
├── anat
│   ├── sub-29666_desc-aparcaseg_dseg.nii.gz
│   ├── sub-29666_desc-aseg_dseg.nii.gz
│   ├── sub-29666_desc-brain_mask.nii.gz
│   ├── sub-29666_desc-preproc_T1w.nii.gz
│   ├── sub-29666_dseg.nii.gz
│   ├── sub-29666_from-MNI152NLin2009cAsym_to-T1w_mode-image_xfm.h5
│   ├── sub-29666_from-T1w_to-fsnative_mode-image_xfm.txt
│   ├── sub-29666_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm.h5
│   ├── sub-29666_hemi-L_inflated.surf.gii
│   ├── sub-29666_hemi-L_midthickness.surf.gii
│   ├── sub-29666_hemi-L_pial.surf.gii
│   ├── sub-29666_hemi-L_smoothwm.surf.gii
│   ├── sub-29666_hemi-R_inflated.surf.gii
│   ├── sub-29666_hemi-R_midthickness.surf.gii
│   ├── sub-29666_hemi-R_pial.surf.gii
│   ├── sub-29666_hemi-R_smoothwm.surf.gii
│   ├── sub-29666_label-CSF_probseg.nii.gz
│   ├── sub-29666_label-GM_probseg.nii.gz
│   ├── sub-29666_label-WM_probseg.nii.gz
│   ├── sub-29666_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
│   ├── sub-29666_space-MNI152NLin2009cAsym_desc-preproc_T1w.nii.gz
│   ├── sub-29666_space-MNI152NLin2009cAsym_dseg.nii.gz
│   ├── sub-29666_space-MNI152NLin2009cAsym_label-CSF_probseg.nii.gz
│   ├── sub-29666_space-MNI152NLin2009cAsym_label-GM_probseg.nii.gz
│   └── sub-29666_space-MNI152NLin2009cAsym_label-WM_probseg.nii.gz
├── figures
│   ├── sub-29666_reconall.svg
│   ├── sub-29666_seg_brainmask.svg
│   ├── sub-29666_ses-1_task-rest_run-1_bbregister.svg
│   ├── sub-29666_ses-1_task-rest_run-1_carpetplot.svg
│   ├── sub-29666_ses-1_task-rest_run-1_ica_aroma.svg
│   ├── sub-29666_ses-1_task-rest_run-1_rois.svg
│   └── sub-29666_t1_2_mni.svg
└── ses-1
    ├── anat
    │   └── sub-29666_ses-1_run-1_from-orig_to-T1w_mode-image_xfm.txt
    └── func
        ├── sub-29666_ses-1_task-rest_run-1_AROMAnoiseICs.csv
        ├── sub-29666_ses-1_task-rest_run-1_bold.dtseries.json
        ├── sub-29666_ses-1_task-rest_run-1_bold.dtseries.nii
        ├── sub-29666_ses-1_task-rest_run-1_desc-confounds_regressors.tsv
        ├── sub-29666_ses-1_task-rest_run-1_desc-MELODIC_mixing.tsv
        ├── sub-29666_ses-1_task-rest_run-1_space-fsaverage5_hemi-L.func.gii
        ├── sub-29666_ses-1_task-rest_run-1_space-fsaverage5_hemi-R.func.gii
        ├── sub-29666_ses-1_task-rest_run-1_space-MNI152NLin2009cAsym_boldref.nii.gz
        ├── sub-29666_ses-1_task-rest_run-1_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
        ├── sub-29666_ses-1_task-rest_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
        ├── sub-29666_ses-1_task-rest_run-1_space-MNI152NLin2009cAsym_desc-smoothAROMAnonaggr_bold.nii.gz
        ├── sub-29666_ses-1_task-rest_run-1_space-T1w_desc-aparcaseg_dseg.nii.gz
        └── sub-29666_ses-1_task-rest_run-1_space-T1w_desc-aseg_dseg.nii.gz

5 directories, 46 files
```

It may be that the structure expected from `xcp_d` is different? Thanks for your help!

Best wishes,
Ioannis

**Comment by smeisler** [comment]
What version fMRIPrep did you use?

**Comment by wizofe** [comment]
For ABIDE2 I used the pre-processed fmriprep from ABIDE consortium as shown here: 
<img width="816" alt="CleanShot 2022-05-08 at 16 26 40@2x" src="https://user-images.githubusercontent.com/22352218/167300893-56bf2e54-5a98-4874-9412-dd2f588acf83.png">

**Comment by smeisler** [comment]
Do you know which version of fMRIprep was used in the ABIDE consortium?  It would be in the logs citation file and the subject html outputs.

**Comment by wizofe** [comment]
Here's the version from the CITATION file (1.2.5):

Results included in this manuscript come from preprocessing performed using fMRIPprep 1.2.5 (Esteban, Markiewicz, et al. (2018); Esteban, Blair, et al. (2018); RRID:SCR_016216), which is based on Nipype 1.1.6 (Gorgolewski et al. (2011); Gorgolewski et al. (2018); RRID:SCR_002502).

**Comment by smeisler** [comment]
This is an old version, it is possible that there have been updates in the BIDS metadata fields that XCP_D expects that are not present in this old version. If you have the raw data, could you reprocess the data with the latest fMRIPrep?

**Comment by wizofe** [comment]
I do have the raw data but it's about 1100 subjects so it will take very long. Is there any way to manually update the BIDS metadata?

**Comment by smeisler** [comment]
For that particular error message you're getting, it should be addressed by adding the following to the dataset_description json file in the fmriprep directory (if old versions made that file).

```
"GeneratedBy": [
        {
            "Name": "fMRIPrep",
            "Version": "21.0.1",
            "CodeURL": "https://github.com/nipreps/fmriprep/archive/21.0.1.tar.gz"
        }
```

If not, you can make a dataset_description.json file in the fmriprep output directory with the following content (for fmriprep 21.0.1):

```
{
    "Name": "fMRIPrep - fMRI PREProcessing workflow",
    "BIDSVersion": "1.4.0",
    "DatasetType": "derivative",
    "GeneratedBy": [
        {
            "Name": "fMRIPrep",
            "Version": "21.0.1",
            "CodeURL": "https://github.com/nipreps/fmriprep/archive/21.0.1.tar.gz"
        }
    ],
    "HowToAcknowledge": "Please cite our paper (https://doi.org/10.1038/s41592-018-0235-4), and include the generated citation boilerplate within the Methods section of the text.",
    "SourceDatasets": [
        {
            "URL": "https://doi.org/",
            "DOI": ""
        }
    ],
    "License": ""
}
```

**Comment by wizofe** [comment]
Unfortunately, still getting the same error (I had already changed the dataset_description.json):

```
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 486, in build_workflow
    retval['workflow'] = init_xcpd_wf (
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/base.py", line 145, in init_xcpd_wf
    single_subj_wf = init_subject_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/base.py", line 396, in init_subject_wf
    bold_postproc_wf = init_boldpostprocess_wf(bold_file=bold_file,
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/bold.py", line 290, in init_boldpostprocess_wf
    executivesummary_wf =init_execsummary_wf(tr=TR,bold_file=bold_file,layout=layout,mem_gb=mem_gbx['timeseries'],
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/execsummary.py", line 44, in init_execsummary_wf
    bold_t1w_reg = fnmatch.filter(all_files, '*' + prefixbb + coregbbregfile[0])[0]
IndexError: list index out of range
```
