### ISSUE TITLE
Nipype workflow connection error

### ISSUE THREAD

**Issue by jbh1091** [PennLINC/xcp_d#397]
Hello, I ran into the following error when trying to run xcp_d on fmriprep-processed data. This is using the latest docker release of both fmriprep and xcp_d. I've used the same workflow with previous version of both containers with no problems. Any advice would be really appreciated since I don't see anything wrong with the fmriprep outputs. Thanks!

Here's my call to docker:

docker run --rm -it -v /path/to/fmriprep:/in/ -v /path/to/output:/out/ pennlinc/xcp_d:latest /in/ /out/ --participant_label 01 --cifti --input-type fmriprep --smoothing 6 --despike -p 36P --lower-bpf 0.009 --upper-bpf 0.08 --motion-filter-type notch --band-stop-min 12 --band-stop-max 18 -r 50 -d 4

And here's the output:

220808-15:09:23,892 nipype.workflow IMPORTANT:

    Running xcp_abcd version 0.1.1+0.g7b09789.dirty:
      * fMRI directory path: /in.
      * Participant list: ['01'].
      * Run identifier: 20220808-150923_970b5450-9d47-4d58-8a47-6f3aa9f47f85.

Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 607, in build_workflow
    retval['workflow'] = init_xcpd_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/base.py", line 144, in init_xcpd_wf
    single_subj_wf = init_subject_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/base.py", line 348, in init_subject_wf
    cifti_postproc_wf = init_ciftipostprocess_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/cifti.py", line 342, in init_ciftipostprocess_wf    workflow.connect([
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 148, in connect
    for srcnode, destnode, _ in connection_list:
ValueError: too many values to unpack (expected 3)

**Comment by kahinimehta** [comment]
Hello! We're currently working on the issue, thanks for pointing it out.

**Comment by kahinimehta** [comment]
Hello! We believe the error should be fixed in our latest "unstable" tag - let us know if this is not the case. Thanks again!

**Comment by jbh1091** [comment]
Hi, thanks for the update! I pulled the new image and unfortunately I'm still getting the same error. Happy to provide any additional information if that would help.

**Comment by kahinimehta** [comment]
Hi! Could you also copy-paste your exact latest docker call and error? Happy to try it locally. Thanks for your patience!

**Comment by jbh1091** [comment]
Sure, here you go:
docker run --rm -it -v /path/to/fmriprep/:/in/ -v /path/to/output:/out/ pennlinc/xcp_d:unstable /in/ /out/ --participant_label 01 --cifti --input-type fmriprep --smoothing 6 --despike -p 36P --lower-bpf 0.009 --upper-bpf 0.08 --motion-filter-type notch --band-stop-min 12 --band-stop-max 18 -r 50 -d 4
220810-14:31:52,701 nipype.workflow IMPORTANT:

    Running xcp_abcd version 0.1.1+2.g4d39cf5.dirty:
      * fMRI directory path: /in.
      * Participant list: ['01'].
      * Run identifier: 20220810-143151_3f6d4721-c074-4fac-8764-5ea3810828b1.


Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 607, in build_workflow
    retval['workflow'] = init_xcpd_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/base.py", line 144, in init_xcpd_wf
    single_subj_wf = init_subject_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/base.py", line 348, in init_subject_wf
    cifti_postproc_wf = init_ciftipostprocess_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/cifti.py", line 342, in init_ciftipostprocess_wf
    workflow.connect([
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 148, in connect
    for srcnode, destnode, _ in connection_list:
ValueError: too many values to unpack (expected 3)

**Comment by kahinimehta** [comment]
It seems we are able to reproduce the error with our older unstable image, but not our latest one. Could you confirm the image ID you have on Docker is "0dd680e198dd"?  @jbh1091

**Comment by jbh1091** [comment]
Pulled the new image and it's running now! Thanks for your help!

**Comment by kahinimehta** [comment]
No worries! Thanks again for bringing this to our notice.
