### ISSUE TITLE
Crash on execsummary_wf.plot_svgx_wf when there is censoring

### ISSUE THREAD

**Issue by danella** [PennLINC/xcp_d#612]
Hi xcp-d crew,

I am running the most recent version of xcp-d 0.2.0 on a single subject. In runs without censoring, the analysis runs without a problem (and the .html output looks great!). However, in runs with censoring, I am getting an error that "arrays must all be same length". I get all outputs except for the Executive Summary. I believe this is because the "regressed_data" input excludes the censored volumes, so it does not match in length to "raw_data" or "filtered motion". Please see the end of the thread on https://neurostars.org/t/question-re-filtering-fd-values/23751/14 for details about code and error messages. Thank you! 

Best,
Danella

**Comment by tsalo** [comment]
Can you share the full log? It's odd that `regressed_data`, `residual_data`, `seg_data`, and `filtered_motion` are all empty.

**Comment by danella** [comment]
Yes, I am not sure why they are empty in the crash log. Here is the report.rst output for the same run:

`Node: single_subject_400_wf (nifti_postprocess_2_wf (execsummary_wf (plot_svgx_wf (surfplotting)
================================================================================================


 Hierarchy : xcpd_wf.single_subject_400_wf.nifti_postprocess_2_wf.execsummary_wf.plot_svgx_wf
 Exec ID : plot_svgx_wf


Original Inputs
---------------


* TR : 1.5
* filtered_motion : /home/xcp_d/BDLONG/Work/xcpd_wf/single_subject_400_wf/nifti_postprocess_2_wf/censoring/sub-400_ses-01_task-movie_space-MNI152NLin6Asym_desc-preproc_bold_desc-filtered_motion.tsv
* mask : /home/xcp_d/BDLONG/Preproc/fmriprep/sub-400/ses-01/func/sub-400_ses-01_task-movie_space-MNI152NLin6Asym_desc-brain_mask.nii.gz
* rawdata : /home/xcp_d/BDLONG/Preproc/fmriprep/sub-400/ses-01/func/sub-400_ses-01_task-movie_space-MNI152NLin6Asym_desc-preproc_bold.nii.gz
* regressed_data : /home/xcp_d/BDLONG/Work/xcpd_wf/single_subject_400_wf/nifti_postprocess_2_wf/regression_wf/3despike_residualized.nii.gz
* residual_data : /home/xcp_d/BDLONG/Work/xcpd_wf/single_subject_400_wf/nifti_postprocess_2_wf/filtering_wf/3despike_residualized_filtered.nii.gz
* seg_data : /home/xcp_d/BDLONG/Work/xcpd_wf/single_subject_400_wf/nifti_postprocess_2_wf/execsummary_wf/resample_parc/tpl-MNI152NLin2009cAsym_res-01_desc-carpet_dseg_trans.nii.gz
`

**Comment by tsalo** [comment]
@kahinimehta and I think we know what conditions lead to the bug. If `--dummytime` is not set, but volumes are flagged for censoring based on FD, this bug might surface. We'll test that out to make sure that's the cause, and then we'll work on a fix.

**Comment by danella** [comment]
I definitely didn't use --dummytime... I use a Siemens scanner, which I believes does this as part of the pre-scan sequence?... I can certainly rerun with it set to something like --dummytime 1 though. Plus, the errors were only on the runs with censoring - the other runs were fine. Thanks!

**Comment by tsalo** [comment]
>I definitely didn't use --dummytime... I use a Siemens scanner, which I believes does this as part of the pre-scan sequence?

Sorry, my initial question was because I got mixed up regarding the bug.

>I can certainly rerun with it set to something like --dummytime 1 though.

I think that would probably solve your immediate problem, but it's no optimal for your data, so hopefully we can make a patch release today.

**Comment by kahinimehta** [comment]
Hi @danella closing this issue for now as the latest push/ unstable version should resolve the bug. Please feel free to re-open if that's not the case!

**Comment by danella** [comment]
Hi @kahinimehta, thanks for your help with this! I tried downloading "latest" from singularity, and then reran the analysis - but I am still getting the same error message. Do you have any additional suggestions? I can also paste in the crash message, but it is essentially the same as before. Thank yoU!

It looks like I am running version xcp_d version 0.2.0+0.g46c71f7.dirty.

Thanks!
