### ISSUE TITLE
execsummary error when multiple BOLD-T1w registration types  ("bbregister", "coreg", "bbreg") exist in session

### ISSUE THREAD

**Issue by madisoth** [PennLINC/xcp_d#663]
## Summary

An error in execsummary_wf when multiple BOLD-T1w registration types and their figures ('*bbregister_bold.svg', '*coreg_bold.svg', '*bbr_bold.svg') exist in the fMRIPrep / NiBabies derivatives

## Additional details

- xcp_d version: 0.2.0

### What were you trying to do?
Process a single fMRIPrep subject/session, in which the figures dir contained the following files:
```
sub-0001_ses-01_desc-about_T1w.html
sub-0001_ses-01_desc-conform_T1w.html
sub-0001_ses-01_desc-reconall_T1w.svg
sub-0001_ses-01_desc-summary_T1w.html
sub-0001_ses-01_dseg.svg
sub-0001_ses-01_fmapid-auto00000_desc-pepolar_fieldmap.svg
sub-0001_ses-01_space-MNI152NLin2009cAsym_T1w.svg
sub-0001_ses-01_space-MNI152NLin6Asym_T1w.svg
sub-0001_ses-01_task-rest_run-01_desc-bbregister_bold.svg
sub-0001_ses-01_task-rest_run-01_desc-carpetplot_bold.svg
sub-0001_ses-01_task-rest_run-01_desc-compcorvar_bold.svg
sub-0001_ses-01_task-rest_run-01_desc-confoundcorr_bold.svg
sub-0001_ses-01_task-rest_run-01_desc-rois_bold.svg
sub-0001_ses-01_task-rest_run-01_desc-sdc_bold.svg
sub-0001_ses-01_task-rest_run-01_desc-summary_bold.html
sub-0001_ses-01_task-rest_run-01_desc-validation_bold.html
sub-0001_ses-01_task-rest_run-02_desc-carpetplot_bold.svg
sub-0001_ses-01_task-rest_run-02_desc-compcorvar_bold.svg
sub-0001_ses-01_task-rest_run-02_desc-confoundcorr_bold.svg
sub-0001_ses-01_task-rest_run-02_desc-coreg_bold.svg
sub-0001_ses-01_task-rest_run-02_desc-rois_bold.svg
sub-0001_ses-01_task-rest_run-02_desc-sdc_bold.svg
sub-0001_ses-01_task-rest_run-02_desc-summary_bold.html
sub-0001_ses-01_task-rest_run-02_desc-validation_bold.html
```
### What did you expect to happen?
Having different types of BOLD-T1w registrations present (bbregister for run-01, coreg for run-02) would not cause an error. 

Because fMRIPrep uses coreg as a fallback for when bbregister produces a subpar result (as determined here: https://github.com/nipreps/fmriprep/blob/6942aed0dfcf4574b1fba313e0cfc110ff7d540c/fmriprep/workflows/bold/registration.py#L821 ), it's possible to have different BOLD-T1w registration types across runs.  

### What actually happened?
XCP-D exited with this error: 
```
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 913, in build_workflow
    retval["workflow"] = init_xcpd_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/base.py", line 159, in init_xcpd_wf
    single_subj_wf = init_subject_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/base.py", line 455, in init_subject_wf
    bold_postproc_wf = postproc_wf_function(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/cifti.py", line 369, in init_ciftipostprocess_wf
    executivesummary_wf = init_execsummary_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflow/execsummary.py", line 209, in init_execsummary_wf
    bold_t1w_registration_file = fnmatch.filter(all_files,
IndexError: list index out of range
```

**Comment by tsalo** [comment]
The code seems to work flexibly around all three figure types:

https://github.com/PennLINC/xcp_d/blob/ee246bb27e44e874c91d3b905e29b2befca8cd78/xcp_d/workflow/execsummary.py#L227-L241

Can you identify what is wrong with the search patterns?

**Comment by tsalo** [comment]
@madisoth have you had a chance to look at this?

**Comment by clane9** [comment]
Hi, I'm having a similar issue

```
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 990, in build_workflow
    retval["workflow"] = init_xcpd_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflows/base.py", line 199, in init_xcpd_wf
    single_subj_wf = init_subject_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflows/base.py", line 716, in init_subject_wf
    postprocess_bold_wf = init_postprocess_bold_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflows/bold.py", line 573, in init_postprocess_nifti_wf
    execsummary_functional_plots_wf = init_execsummary_functional_plots_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/workflows/execsummary.py", line 384, in init_execsummary_functional_plots_wf
    bold_t1w_registration_file = fnmatch.filter(
IndexError: list index out of range
```

Here are the contents of my subject's fmriprep `figures/` directory:

```
sub-0025921_run-1_desc-conform_T1w.html
sub-0025921_run-1_dseg.svg
sub-0025921_run-1_space-MNI152NLin2009cAsym_T1w.svg
sub-0025921_ses-1_desc-about_T1w.html
sub-0025921_ses-1_desc-summary_T1w.html
sub-0025921_ses-1_task-rest_run-1_desc-carpetplot_bold.svg
sub-0025921_ses-1_task-rest_run-1_desc-compcorvar_bold.svg
sub-0025921_ses-1_task-rest_run-1_desc-confoundcorr_bold.svg
sub-0025921_ses-1_task-rest_run-1_desc-flirtbbr_bold.svg
sub-0025921_ses-1_task-rest_run-1_desc-rois_bold.svg
sub-0025921_ses-1_task-rest_run-1_desc-summary_bold.html
sub-0025921_ses-1_task-rest_run-1_desc-validation_bold.html
sub-0025921_ses-2_task-rest_run-1_desc-carpetplot_bold.svg
sub-0025921_ses-2_task-rest_run-1_desc-compcorvar_bold.svg
sub-0025921_ses-2_task-rest_run-1_desc-confoundcorr_bold.svg
sub-0025921_ses-2_task-rest_run-1_desc-flirtbbr_bold.svg
sub-0025921_ses-2_task-rest_run-1_desc-rois_bold.svg
sub-0025921_ses-2_task-rest_run-1_desc-summary_bold.html
sub-0025921_ses-2_task-rest_run-1_desc-validation_bold.html
```

It seems the issue is that the `flirtbbr` desc is not matched by any of the filters here:

https://github.com/PennLINC/xcp_d/blob/c6ef7b4079d3e2c2aa3110abbb3fd3eb1b6c55e1/xcp_d/workflows/execsummary.py#L381-L391

I'm using fMRIprep v20.2.7 and XCP-D v0.5.2. I ran fMRIprep with `--fs-no-reconall`.

**Comment by tsalo** [comment]
Thanks @clane9. I'll open a PR to fix this tomorrow.

**Comment by clane9** [comment]
Sorry, got another one: `flirtnobbr`. Processing a different dataset but otherwise everything the same about how I'm running fMRIprep 🤷.

```
sub-MSC01_dseg.svg
sub-MSC01_ses-func01_desc-about_T1w.html
sub-MSC01_ses-func01_desc-summary_T1w.html
sub-MSC01_ses-func01_task-rest_desc-carpetplot_bold.svg
sub-MSC01_ses-func01_task-rest_desc-compcorvar_bold.svg
sub-MSC01_ses-func01_task-rest_desc-confoundcorr_bold.svg
sub-MSC01_ses-func01_task-rest_desc-flirtnobbr_bold.svg
sub-MSC01_ses-func01_task-rest_desc-rois_bold.svg
sub-MSC01_ses-func01_task-rest_desc-summary_bold.html
sub-MSC01_ses-func01_task-rest_desc-validation_bold.html
```

**Comment by tsalo** [comment]
I just released 0.6.0rc2. It'll take a couple of hours to deploy to DockerHub. Would you mind pulling that version and trying it out when you have a chance?

Over time, I'll try to make the list of descriptions that could be used in the registration figures comprehensive, but in the mean time, this new release should just leave that section empty in the executive summary instead of raising an error.

**Comment by clane9** [comment]
So I still have a similar issue on 0.6.0rc2. Here is one failing subject's figures directory:

```
$ ls figures/
sub-0027111_run-1_desc-conform_T1w.html
sub-0027111_run-1_dseg.svg
sub-0027111_run-1_space-MNI152NLin2009cAsym_T1w.svg
sub-0027111_ses-1_desc-about_T1w.html
sub-0027111_ses-1_desc-summary_T1w.html
sub-0027111_ses-1_task-rest_run-1_desc-carpetplot_bold.svg
sub-0027111_ses-1_task-rest_run-1_desc-compcorvar_bold.svg
sub-0027111_ses-1_task-rest_run-1_desc-confoundcorr_bold.svg
sub-0027111_ses-1_task-rest_run-1_desc-flirtbbr_bold.svg
sub-0027111_ses-1_task-rest_run-1_desc-rois_bold.svg
sub-0027111_ses-1_task-rest_run-1_desc-summary_bold.html
sub-0027111_ses-1_task-rest_run-1_desc-validation_bold.html
sub-0027111_ses-2_task-rest_run-1_desc-carpetplot_bold.svg
sub-0027111_ses-2_task-rest_run-1_desc-compcorvar_bold.svg
sub-0027111_ses-2_task-rest_run-1_desc-confoundcorr_bold.svg
sub-0027111_ses-2_task-rest_run-1_desc-flirtbbr_bold.svg
sub-0027111_ses-2_task-rest_run-1_desc-rois_bold.svg
sub-0027111_ses-2_task-rest_run-1_desc-summary_bold.html
sub-0027111_ses-2_task-rest_run-1_desc-validation_bold.html
sub-0027111_ses-3_task-rest_run-1_desc-carpetplot_bold.svg
sub-0027111_ses-3_task-rest_run-1_desc-compcorvar_bold.svg
sub-0027111_ses-3_task-rest_run-1_desc-confoundcorr_bold.svg
sub-0027111_ses-3_task-rest_run-1_desc-flirtnobbr_bold.svg
sub-0027111_ses-3_task-rest_run-1_desc-rois_bold.svg
sub-0027111_ses-3_task-rest_run-1_desc-summary_bold.html
sub-0027111_ses-3_task-rest_run-1_desc-validation_bold.html
```

The issue is that there are multiple sessions with different variants of the registration figure. Sessions 1 and 2 have a match for `'flirtbbr'` while session 3 has `'flirtnobbr'` for some reason. As a result, `bold_t1w_registration_files` is nonempty but the `fnmatch.filter()` result is. Perhaps you could check for a match after `fnmatch.filter()` instead of after `layout.get()`?

https://github.com/PennLINC/xcp_d/blob/f38dae268dced408b04db9d03625e6fe56b07aaa/xcp_d/workflows/execsummary.py#L381-L394

Thanks so much, sorry for all the trouble!

**Comment by tsalo** [comment]
Was there an error or was the figure just missing in the executive summary?

**Comment by clane9** [comment]
Thanks so much for the super quick response! Yup I think your PR should fix it.
